name: demo workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-postman-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"

      - name: Install Newman
        run: npm install -g newman

      - name: Install HTMLExtra Reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Create directory for results
        run: mkdir -p testResult

      - name: Run Postman collection
        run: |
          newman run Simform_gorest_API_collection.json \
            -e Simform_gorest_environment.json \
            -r htmlextra \
            --reporter-htmlextra-export testResult/report.html || true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: NewmanReports
          path: testResult
