name: pipeline_12

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-postman-collection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman collection with Newman
      run: |
        mkdir -p reports
        newman run Simform_gorest_API_collection.json \
          --environment Simform_gorest_environment.json \
          --reporters cli,json \
          --reporter-json-export reports/newman-report.json

    - name: Upload Newman report
      uses: actions/upload-artifact@v3
      with:
        name: newman-report
        path: reports/newman-report.json
