# This is a basic workflow to help you get started with Actions

name: This is an API Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # install node js
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"

      # install new man
      - name: Install newman
        run: npm install -g newman
              
      - name: Install HTMLExtra Reporter
        run: npm install -g newman-reporter-htmlextra
        
      # Make directory to upload the test result
      - name: Make directory for result
        run: mkdir -p testResult

      # Run the Postman collection
      - name: Run Postman collection
        run: |
         newman run Simform_gorest_API_collection.json -e Simform_gorest_environment.json -r htmlextra --reporter-htmlextra-export testResult/report.html || true

      # store the result in folder
      - name: Output the run details
        uses: actions/upload-artifact@v4
        with:
           name: RunReports
           path: testResult
